reverse a list not using reverse method

In [1]:
list_to_reverse = [0,1,2,3,4,5,6,7,8,9]
reversed_list = list_to_reverse[::-1]
print(reversed_list)

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


using list comprehension divide reversed list by 2

In [14]:
divided_list = [i/2 for i in reversed_list]
print(divided_list)

[4.5, 4.0, 3.5, 3.0, 2.5, 2.0, 1.5, 1.0, 0.5, 0.0]


Linear algebra
 - vector math - what is a vector - has magnitude and direction
 - PCA - principle reducing variables in a dataset
 - one-hot encoding - convert categorical to numerical - don't need 2 columns - one column predicts another - multicollinear
 2 variables highly correlated

# Vectors


In [21]:
import numpy as np
v = np.array([[1],[2],[3]])
v2 = np.array([[-1],[-2],[-3]])
print(v)

[[1]
 [2]
 [3]]


In [17]:
print(v.T)

[[1 2 3]]


In [18]:
v.shape

(3, 1)

# Matrices

In [19]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
M.shape

(3, 3)

In [23]:
# Scalar
x=3.5

# zipping
new_matrix = list(zip(v,v2))
new_matrix

[(array([1]), array([-1])),
 (array([2]), array([-2])),
 (array([3]), array([-3]))]

In [24]:
type(new_matrix)

list

Dot product - taking 2 vectors and compute dot product, produces scalar value


In [25]:
# dot product of a and b = ax*bx + ay*by - if know x, y coordinates
# if not ||a|| * ||b|| * cosine (of angle)


# dot product

We use the dot product to multiply vectors. With 2D vectors, this is the same as matrix multiplication, and we produce a scaler value (a number, not a vector).

Result tells you the degree to which the vectors interact, or the interaction between similar dimensions.

Why do we care? rendering, force diagrams, solar panel tracking

In [26]:
print(v.T)
print(v)

[[1 2 3]]
[[1]
 [2]
 [3]]


In [28]:
# 1*1 + 2*2 + 3*3
np.dot(v.T,v)

array([[14]])

In [29]:
#directionality example
north = np.array([0,1])
east = np.array([1,0])
south = np.array([0,-1])
west = np.array([-1,0])

# to what degree are the two directions the same
np.dot(north,south)

-1

In [30]:
np.dot(north,east) #have nothing in common

0

In [32]:
# to what degree are north and south the same? both have a common x axis (which is 0)
# create an example
np.dot(north, south)

-1

In [33]:
# pythagoream theorem

# Cross product

Type of vector multiplication, but it shows the interaction between different components expressed by the vector. It tracks all of the cross interactions between dimensions

When you compute the cross product, you get a new vector, not a scalar, that is perpendicular to both input vectors.

* In each part of the cross product calculation, you are leaving out an interaction. * this could be stated better

Why do we care? torque and "moment" of a force
Moment = measure of the tendency to rotate about a particular point
right hand rule

In [34]:
print(v)
print(v2)

[[1]
 [2]
 [3]]
[[-1]
 [-2]
 [-3]]


In [36]:
np.cross(v, v2, axisa=0,axisb=0 )

array([[0, 0, 0]])

# Orthogonality

Two vectors are orthoganol if they're perpendicular.
The dot product is 0 or the identity matrix.

This is LaTeX
$$ A \cdot A^T = I $$

In [38]:
#this is an identity matrix


M = np.array([[1,0,0],
            [0,1,0],
            [0,0,1]])
M

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [39]:
M.T

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [40]:
# a test for orthoganilty is if the matrix and its transpose equal the identity matrix
np.dot(M,M.T)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [43]:
M = np.array([[1,2,3], [4,5,6],[7,8,9]])
M.T                                

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [44]:
t = np.array([[1,1,1],[2,2,2],[3,3,3]])
t

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [45]:
t.T

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [46]:
np.dot(t,t.T)


array([[ 3,  6,  9],
       [ 6, 12, 18],
       [ 9, 18, 27]])

## why is error handling important?
Make sure something doesn't stop


In [62]:
def countdown(n):
    #print(n)
    #count backwards from n until we get to 0
    if n>0:
        #stuff
        #print(n)
        countdown(n-1)
        # if you print after you call the function again
        # it has to almost unwind until it gets to the 
        #stopping condition
        #last in, first out (LIFO) stack
    else:
        return #stopping condition - terminates the recursion
    print(n)

In [63]:
countdown(2)

1
2
